# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_hired',
            new_name='date_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
